CREATE DATABASE IF NOT EXISTS `$$DB_NAME$$` CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER `$$MYSQL_USER`@'%' IDENTIFIED BY `$$MYSQL_PASSWORD`;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO `$$MYSQL_USER`@'%';
FLUSH PRIVILEGES;
SET PASSWORD FOR 'root'@'localhost' = PASSWORD(`$$MYSQL_ROOT_PASSWORD`);